### ISSUE TITLE
Use `alert` package instead of `notifications`

### ISSUE THREAD

**Issue by gsingh93** [inickey/org-clock-reminder#2]
Would you be able to switch from using the `notifications` package to using the [`alert`](https://github.com/jwiegley/alert) package? It would allow macOS users to use this package, and it would also allow more customization options for the notification.

**Comment by inickey** [comment]
Hi! Thanks for your suggestion.

Honestly I'm surprised that `notifications` package isn't working on macOS. I will investigate this issue in the coming days and try to solve this problem

**Comment by gsingh93** [comment]
Thanks! The specific issue with `notifications` is it seems to require DBus, which doesn't work on macOS. The error message I get says "Emacs not compiled with dbus support".

**Comment by gsingh93** [comment]
@acowley, it looks like you've fixed this in your fork. Would you mind submitting a PR to fix this in this repo?

**Comment by inickey** [comment]
@swflint fixed this in his PR #3 so I think this issue can be closed

**Comment by acowley** [comment]
Sorry this fell off my radar, @gsingh93! I've been using my fork ever since I created it, and it has worked well across various Linux distributions and macOS versions. It looks like this new PR lets you set it up to use `alert`, so maybe providing an example of how to make it work on macOS would be okay. I think having it just work out of the box via `alert` is a bit nicer, but I'm content continuing to use my fork as there's nothing more I've noticed wanting from the package.

**Comment by swflint** [comment]
I don't (currently) use `alert` so I wasn't sure how best to integrate it.  Additionally, `alert` is a separate dependency, so (even with recent changes somewhat complicating things), it does add more complication.

**Comment by acowley** [comment]
@swflint The [diff](https://github.com/inickey/org-clock-reminder/compare/master...acowley:org-clock-reminder:alert) to use `alert` was thankfully not at all complicated.

**Comment by swflint** [comment]
The diff isn't complicated, but requiring `alert` complicates downstream users' configurations.

**Comment by gsingh93** [comment]
The following configuration worked for me, so closing this issue now:
```elisp
(use-package org-clock-reminder
  :ensure t
  :quelpa (org-clock-reminder :fetcher github :repo "inickey/org-clock-reminder" :files ("*.el"))
  :config
  (defun org-clock-reminder-alert (title message)
    "Sends MESSAGE with given TITLE with `alert'."
    (let ((icon-path (org-clock-reminder--icon)))
      (alert message
             :title title
             :category 'org-clock-reminder
             :icon icon-path)))

  ;; The default `notifications' library doesn't support macOS, so use the
  ;; `alert' package instead
  (when (eq system-type 'darwin)
    (setq org-clock-reminder-notifiers '(list org-clock-reminder-alert)))
  
  (org-clock-reminder-mode))

(use-package alert
  :ensure t
  :config
  ;; Use `terminal-notifier' for notifications on macOS (install with `brew')
  (when (eq system-type 'darwin)
    (setq alert-default-style 'notifier)))
```
